package com.pizzeria.models;

public enum Toppings {
	LETTUCE, TOMATO, CHEESE, SAUSAGE, ONION, 
	OLIVE, BACON, MEATBALL, CHICKEN, PEPPERONI,
	PASTA, SPINACH, BROCCOLI, PEPPER, ANCHOVY,
	PINEAPPLE, GARLIC, CARROT, ARTICHOKE, BASIL,
	CILANTRO, CROUTON, JALAPENO, MUSHROOM, OREGANO,
	SALAMI, HAM
}
